#What the hell is this?
#What the fuck?
#This is the new document you fools
#kfine
import numpy as np
def function(element,charge):
	#initialize tuples 
	#element tuples
	element = (null,null,He, Li ,Be ,B ,C ,N ,O ,F ,Ne ,Na ,Mg ,Al ,Si ,P ,S ,Cl ,Ar ,K ,Ca ,Sc ,Ti,V ,Cr,Mn,Fe ,Co ,Ni ,Cu ,Zn ,Ga ,Ge ,As ,Se ,Br ,Kr ,Rb ,Sr ,Y ,Zr ,Mo ,Tc ,Ru ,Rh ,Pd ,Ag ,Cd ,In ,Sn ,Sb ,Te ,I ,Xe ,Cs ,Ba ,La ,Ce ,Pr ,Nd ,Pm ,Sm ,Eu ,Gd ,Tb ,Dy ,Ho ,Er ,Tm ,Yb ,Lu ,Hf ,Ta ,W ,Re ,Os ,Ir ,Pt ,Au ,Hg ,Tl ,Pb ,Bi ,Po ,At ,Rn ,Fr ,Ra ,Ac ,Th ,Pa,U,Np,Pu,Am,Cm ,Bk,Cf,Es)
	#individual tuples
	He = [null]
	Li = [null]
	Be = [null]
	B = [null]
	C = [null]
	N = [null]
	O = [null]
	F = [null]
	Ne = [null]
	Na = [null]
	Mg = [null]
	Al = [null]
	Si = [null]
	P = [null]
	S = [null]
	Cl = [null]
	Ar = [null]
	K = [null]
	Ca = [null]
	Sc = [null]
	Ti = [null]
	V = [null]
	Cr = [null]
	Mn = [null]
	Fe = [null]
	Co = [null]
	Ni = [null]
	Cu = [null]
	Zn = [null]
	Ga = [null]
	Ge = [null]
	As = [null]
	Se = [null]
	Br = [null]
	Kr = [null]
	Rb = [null]
	Sr = [null]
	Y = [null]
	Zr = [null]
	Mo = [null]
	Tc = [null]
	Ru = [null]
	Rh = [null]
	Pd = [null]
	Ag = [null]
	Cd = [null]
	In = [null]
	Sn = [null]
	Sb = [null]
	Te = [null]
	I = [null]
	Xe = [null]
	Cs = [null]
	Ba = [null]
	La = [null]
	Ce = [null]
	Pr = [null]
	Nd = [null]
	Pm = [null]
	Sm = [null]
	Eu = [null]
	Gd = [null]
	Tb = [null]
	Dy = [null]
	Ho = [null]
	Er = [null]
	Tm = [null]
	Yb = [null]
	Lu = [null]
	Hf = [null]
	Ta = [null]
	W = [null]
	Re = [null]
	Os = [null]
	Ir = [null]
	Pt = [null]
	Au = [null]
	Hg = [null]
	Tl = [null]
	Pb = [null]
	Bi = [null]
	Po = [null]
	At = [null]
	Rn = [null]
	Fr = [null]
	Ra = [null]
	Ac = [null]
	Th = [null]
	Pa = [null]
	U = [null]
	Np = [null]
	Pu = [null]
	Am = [null]
	Cm = [null]
	Bk = [null]
	#GO BEARS!!!!
	Cf = [null]
	Es = [null]
	pass
